using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

public partial class index : System.Web.UI.Page
{
    //316
    string sql;
    DataTable dt;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            cal_counter();//計數器
        }
        sql = "SELECT name, url FROM logistics";
        dt = somecode.GetDataTable(sql);
        HyperLink1.Text = dt.Rows[0][0].ToString();
        HyperLink1.NavigateUrl = dt.Rows[0][1].ToString();
        HyperLink2.Text = dt.Rows[1][0].ToString();
        HyperLink2.NavigateUrl = dt.Rows[1][1].ToString();
        HyperLink3.Text = dt.Rows[2][0].ToString();
        HyperLink3.NavigateUrl = dt.Rows[2][1].ToString();
        HyperLink4.Text = dt.Rows[3][0].ToString();
        HyperLink4.NavigateUrl = dt.Rows[3][1].ToString();
        HyperLink5.Text = dt.Rows[4][0].ToString();
        HyperLink5.NavigateUrl = dt.Rows[4][1].ToString();
        HyperLink6.Text = dt.Rows[5][0].ToString();
        HyperLink6.NavigateUrl = dt.Rows[5][1].ToString();
        HyperLink7.Text = dt.Rows[6][0].ToString();
        HyperLink7.NavigateUrl = dt.Rows[6][1].ToString();

        sql = "SELECT name, url, pic FROM zhongdikai";
        dt = somecode.GetDataTable(sql);

        m1_left_U.NavigateUrl = dt.Rows[3][1].ToString();
        m1_left_U.ImageUrl = "image/lelecoco/" + dt.Rows[3][2].ToString();

        m1_right_L_U_LTP1.Text = dt.Rows[4][0].ToString();
        m1_right_L_U_LHL01.NavigateUrl = dt.Rows[4][1].ToString();
        m1_right_L_U_LHL01.ImageUrl = "image/lelecoco/" + dt.Rows[4][2].ToString();
        m1_right_L_U_LTP2.Text = dt.Rows[5][0].ToString();
        m1_right_L_U_LHL02.NavigateUrl = dt.Rows[5][1].ToString();
        m1_right_L_U_LHL02.ImageUrl = "image/lelecoco/" + dt.Rows[5][2].ToString();
        m1_right_L_U_LTP3.Text = dt.Rows[6][0].ToString();
        m1_right_L_U_LHL03.NavigateUrl = dt.Rows[6][1].ToString();
        m1_right_L_U_LHL03.ImageUrl = "image/lelecoco/" + dt.Rows[6][2].ToString();
        m1_right_L_U_LTP4.Text = dt.Rows[7][0].ToString();
        m1_right_L_U_LHL04.NavigateUrl = dt.Rows[7][1].ToString();
        m1_right_L_U_LHL04.ImageUrl = "image/lelecoco/" + dt.Rows[7][2].ToString();
        m1_right_L_U_LTP5.Text = dt.Rows[8][0].ToString();
        m1_right_L_U_LHL05.NavigateUrl = dt.Rows[8][1].ToString();
        m1_right_L_U_LHL05.ImageUrl = "image/lelecoco/" + dt.Rows[8][2].ToString();
        m1_right_L_U_LTP6.Text = dt.Rows[9][0].ToString();
        m1_right_L_U_LHL06.NavigateUrl = dt.Rows[9][1].ToString();
        m1_right_L_U_LHL06.ImageUrl = "image/lelecoco/" + dt.Rows[9][2].ToString();

        m1_right_L_U_RTP1.Text = dt.Rows[10][0].ToString();
        m1_right_L_U_RHL01.NavigateUrl = dt.Rows[10][1].ToString();
        m1_right_L_U_RHL01.ImageUrl = "image/lelecoco/" + dt.Rows[10][2].ToString();
        m1_right_L_U_RTP2.Text = dt.Rows[11][0].ToString();
        m1_right_L_U_RHL02.NavigateUrl = dt.Rows[11][1].ToString();
        m1_right_L_U_RHL02.ImageUrl = "image/lelecoco/" + dt.Rows[11][2].ToString();
        m1_right_L_U_RTP3.Text = dt.Rows[12][0].ToString();
        m1_right_L_U_RHL03.NavigateUrl = dt.Rows[12][1].ToString();
        m1_right_L_U_RHL03.ImageUrl = "image/lelecoco/" + dt.Rows[12][2].ToString();

        m1_right_L_D_L1.NavigateUrl = dt.Rows[13][1].ToString();
        m1_right_L_D_L1.ImageUrl = "image/lelecoco/" + dt.Rows[13][2].ToString();
        m1_right_L_D_L2.Text = dt.Rows[14][0].ToString();
        m1_right_L_D_L2.NavigateUrl = dt.Rows[14][1].ToString();
        m1_right_L_D_L3.Text = dt.Rows[15][0].ToString();
        m1_right_L_D_L3.NavigateUrl = dt.Rows[15][1].ToString();
        m1_right_L_D_L4.Text = dt.Rows[16][0].ToString();
        m1_right_L_D_L4.NavigateUrl = dt.Rows[16][1].ToString();
        m1_right_L_D_L5.Text = dt.Rows[17][0].ToString();
        m1_right_L_D_L5.NavigateUrl = dt.Rows[17][1].ToString();

        m1_right_L_D_R1.NavigateUrl = dt.Rows[18][1].ToString();
        m1_right_L_D_R1.ImageUrl = "image/lelecoco/" + dt.Rows[18][2].ToString();
        m1_right_L_D_R2.Text = dt.Rows[19][0].ToString();
        m1_right_L_D_R2.NavigateUrl = dt.Rows[19][1].ToString();
        m1_right_L_D_R3.Text = dt.Rows[20][0].ToString();
        m1_right_L_D_R3.NavigateUrl = dt.Rows[20][1].ToString();
        m1_right_L_D_R4.Text = dt.Rows[21][0].ToString();
        m1_right_L_D_R4.NavigateUrl = dt.Rows[21][1].ToString();
        m1_right_L_D_R5.Text = dt.Rows[22][0].ToString();
        m1_right_L_D_R5.NavigateUrl = dt.Rows[22][1].ToString();

        m1_right_R_U1.Text = dt.Rows[23][0].ToString() + " ";
        m1_right_R_U1.NavigateUrl = dt.Rows[23][1].ToString();
        m1_right_R_U2.Text = dt.Rows[24][0].ToString() + " ";
        m1_right_R_U2.NavigateUrl = dt.Rows[24][1].ToString();
        m1_right_R_U3.Text = dt.Rows[25][0].ToString() + " ";
        m1_right_R_U3.NavigateUrl = dt.Rows[25][1].ToString();
        m1_right_R_U4.Text = dt.Rows[26][0].ToString() + " ";
        m1_right_R_U4.NavigateUrl = dt.Rows[26][1].ToString();
        m1_right_R_U5.Text = dt.Rows[27][0].ToString() + " ";
        m1_right_R_U5.NavigateUrl = dt.Rows[27][1].ToString();
        m1_right_R_U6.Text = dt.Rows[28][0].ToString() + " ";
        m1_right_R_U6.NavigateUrl = dt.Rows[28][1].ToString();
        m1_right_R_U7.Text = dt.Rows[29][0].ToString() + " ";
        m1_right_R_U7.NavigateUrl = dt.Rows[29][1].ToString();
        m1_right_R_U8.Text = dt.Rows[30][0].ToString() + " ";
        m1_right_R_U8.NavigateUrl = dt.Rows[30][1].ToString();
        m1_right_R_U9.Text = dt.Rows[31][0].ToString() + " ";
        m1_right_R_U9.NavigateUrl = dt.Rows[31][1].ToString();
        m1_right_R_U10.Text = dt.Rows[32][0].ToString() + " ";
        m1_right_R_U10.NavigateUrl = dt.Rows[32][1].ToString();

        m1_right_R_D1.NavigateUrl = dt.Rows[33][1].ToString();
        m1_right_R_D1.ImageUrl = "image/lelecoco/" + dt.Rows[33][2].ToString();
        m1_right_R_D2.NavigateUrl = dt.Rows[34][1].ToString();
        m1_right_R_D2.ImageUrl = "image/lelecoco/" + dt.Rows[34][2].ToString();
        m1_right_R_D3.NavigateUrl = dt.Rows[35][1].ToString();
        m1_right_R_D3.ImageUrl = "image/lelecoco/" + dt.Rows[35][2].ToString();
        m1_right_R_D4.NavigateUrl = dt.Rows[36][1].ToString();
        m1_right_R_D4.ImageUrl = "image/lelecoco/" + dt.Rows[36][2].ToString();
        m1_right_R_D5.NavigateUrl = dt.Rows[37][1].ToString();
        m1_right_R_D5.ImageUrl = "image/lelecoco/" + dt.Rows[37][2].ToString();

        advertising1_1.NavigateUrl = dt.Rows[38][1].ToString();
        advertising1_1.ImageUrl = "image/lelecoco/" + dt.Rows[38][2].ToString();
        advertising1_2.NavigateUrl = dt.Rows[39][1].ToString();
        advertising1_2.ImageUrl = "image/lelecoco/" + dt.Rows[39][2].ToString();
        advertising1_3.NavigateUrl = dt.Rows[220][1].ToString();
        advertising1_3.ImageUrl = "image/lelecoco/" + dt.Rows[220][2].ToString();

        m2_left_U.Text = "<a href='" + dt.Rows[40][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[40][2].ToString() + "'/></a><a href='" + dt.Rows[41][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[41][2].ToString() + "'/></a><a href='" + dt.Rows[42][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[42][2].ToString() + "'/></a>";
        m2_left_D.Text = "<a href='" + dt.Rows[43][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[43][2].ToString() + "'/></a><a href='" + dt.Rows[44][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[44][2].ToString() + "'/></a><a href='" + dt.Rows[45][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[45][2].ToString() + "'/></a>";
        m2_right_L.Text = "<a href='" + dt.Rows[46][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[46][2].ToString() + "'/></a><a href='" + dt.Rows[47][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[47][2].ToString() + "'/></a><a href='" + dt.Rows[48][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[48][2].ToString() + "'/></a><a href='" + dt.Rows[49][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[49][2].ToString() + "'/></a><a href='" + dt.Rows[50][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[50][2].ToString() + "'/></a>";
        m2_right_R_U.Text = "<a href='" + dt.Rows[51][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[51][2].ToString() + "'/></a><a href='" + dt.Rows[52][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[52][2].ToString() + "'/></a><a href='" + dt.Rows[53][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[53][2].ToString() + "'/></a>";
        m2_right_R_D.Text = "<a href='" + dt.Rows[54][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[54][2].ToString() + "'/></a><a href='" + dt.Rows[55][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[55][2].ToString() + "'/></a><a href='" + dt.Rows[56][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[56][2].ToString() + "'/></a>";

        VIP_TI1.NavigateUrl = dt.Rows[57][1].ToString();
        VIP_TI1.ImageUrl = "image/lelecoco/" + dt.Rows[57][2].ToString();
        VIP_TT1.Text = dt.Rows[57][0].ToString();
        VIP_TT1.NavigateUrl = dt.Rows[57][1].ToString();
        VIP_TI2.NavigateUrl = dt.Rows[58][1].ToString();
        VIP_TI2.ImageUrl = "image/lelecoco/" + dt.Rows[58][2].ToString();
        VIP_TT2.Text = dt.Rows[58][0].ToString();
        VIP_TT2.NavigateUrl = dt.Rows[58][1].ToString();
        VIP_TI3.NavigateUrl = dt.Rows[59][1].ToString();
        VIP_TI3.ImageUrl = "image/lelecoco/" + dt.Rows[59][2].ToString();
        VIP_TT3.Text = dt.Rows[59][0].ToString();
        VIP_TT3.NavigateUrl = dt.Rows[59][1].ToString();
        VIP_TI4.NavigateUrl = dt.Rows[60][1].ToString();
        VIP_TI4.ImageUrl = "image/lelecoco/" + dt.Rows[60][2].ToString();
        VIP_TT4.Text = dt.Rows[60][0].ToString();
        VIP_TT4.NavigateUrl = dt.Rows[60][1].ToString();
        VIP_TI5.NavigateUrl = dt.Rows[61][1].ToString();
        VIP_TI5.ImageUrl = "image/lelecoco/" + dt.Rows[61][2].ToString();
        VIP_TT5.Text = dt.Rows[61][0].ToString();
        VIP_TT5.NavigateUrl = dt.Rows[61][1].ToString();
        VIP_TI6.NavigateUrl = dt.Rows[62][1].ToString();
        VIP_TI6.ImageUrl = "image/lelecoco/" + dt.Rows[62][2].ToString();
        VIP_TT6.Text = dt.Rows[62][0].ToString();
        VIP_TT6.NavigateUrl = dt.Rows[62][1].ToString();
        VIP_TI7.NavigateUrl = dt.Rows[63][1].ToString();
        VIP_TI7.ImageUrl = "image/lelecoco/" + dt.Rows[63][2].ToString();
        VIP_TT7.Text = dt.Rows[63][0].ToString();
        VIP_TT7.NavigateUrl = dt.Rows[63][1].ToString();
        VIP_TI8.NavigateUrl = dt.Rows[64][1].ToString();
        VIP_TI8.ImageUrl = "image/lelecoco/" + dt.Rows[64][2].ToString();
        VIP_TT8.Text = dt.Rows[64][0].ToString();
        VIP_TT8.NavigateUrl = dt.Rows[64][1].ToString();

        m5_left_U.Text = "<a href='" + dt.Rows[65][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[65][2].ToString() + "'/></a><a href='" + dt.Rows[66][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[66][2].ToString() + "'/></a><a href='" + dt.Rows[67][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[67][2].ToString() + "'/></a>";
        m5_left_D.Text = "<a href='" + dt.Rows[68][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[68][2].ToString() + "'/></a><a href='" + dt.Rows[69][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[69][2].ToString() + "'/></a><a href='" + dt.Rows[70][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[70][2].ToString() + "'/></a>";
        m5_right_U.Text = "<a href='" + dt.Rows[71][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[71][2].ToString() + "'/></a><a href='" + dt.Rows[72][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[72][2].ToString() + "'/></a><a href='" + dt.Rows[73][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[73][2].ToString() + "'/></a>";
        m5_right_D.Text = "<a href='" + dt.Rows[74][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[74][2].ToString() + "'/></a><a href='" + dt.Rows[75][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[75][2].ToString() + "'/></a><a href='" + dt.Rows[76][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[76][2].ToString() + "'/></a>";

        advertising4_1.NavigateUrl = dt.Rows[77][1].ToString();
        advertising4_1.ImageUrl = "image/lelecoco/" + dt.Rows[77][2].ToString();
        advertising4_2.NavigateUrl = dt.Rows[78][1].ToString();
        advertising4_2.ImageUrl = "image/lelecoco/" + dt.Rows[78][2].ToString();
        advertising4_3.NavigateUrl = dt.Rows[79][1].ToString();
        advertising4_3.ImageUrl = "image/lelecoco/" + dt.Rows[79][2].ToString();
        advertising4_4.NavigateUrl = dt.Rows[80][1].ToString();
        advertising4_4.ImageUrl = "image/lelecoco/" + dt.Rows[80][2].ToString();
        advertising4_5.NavigateUrl = dt.Rows[81][1].ToString();
        advertising4_5.ImageUrl = "image/lelecoco/" + dt.Rows[81][2].ToString();

        CR_main_left_L.NavigateUrl = dt.Rows[82][1].ToString();
        CR_main_left_L.ImageUrl = "image/lelecoco/" + dt.Rows[82][2].ToString();
        CR_main_left_R.NavigateUrl = dt.Rows[83][1].ToString();
        CR_main_left_R.ImageUrl = "image/lelecoco/" + dt.Rows[83][2].ToString();
        CR_main_right_L_L.NavigateUrl = dt.Rows[84][1].ToString();
        CR_main_right_L_L.ImageUrl = "image/lelecoco/" + dt.Rows[84][2].ToString();
        CR_main_right_L_R.NavigateUrl = dt.Rows[85][1].ToString();
        CR_main_right_L_R.ImageUrl = "image/lelecoco/" + dt.Rows[85][2].ToString();
        CR_main_right_R.NavigateUrl = dt.Rows[86][1].ToString();
        CR_main_right_R.ImageUrl = "image/lelecoco/" + dt.Rows[86][2].ToString();

        HI_Tab1IMG.Text = dt.Rows[87][0].ToString();
        HI_TAB1_1.NavigateUrl = dt.Rows[88][1].ToString();
        HI_TAB1_1.ImageUrl = "image/lelecoco/" + dt.Rows[88][2].ToString();
        HI_TAB1_2.NavigateUrl = dt.Rows[89][1].ToString();
        HI_TAB1_2.ImageUrl = "image/lelecoco/" + dt.Rows[89][2].ToString();
        HI_TAB1_3.NavigateUrl = dt.Rows[90][1].ToString();
        HI_TAB1_3.ImageUrl = "image/lelecoco/" + dt.Rows[90][2].ToString();
        HI_TAB1_4.NavigateUrl = dt.Rows[91][1].ToString();
        HI_TAB1_4.ImageUrl = "image/lelecoco/" + dt.Rows[91][2].ToString();
        HI_TAB1_5.NavigateUrl = dt.Rows[92][1].ToString();
        HI_TAB1_5.ImageUrl = "image/lelecoco/" + dt.Rows[92][2].ToString();

        HI_Tab2IMG.Text = dt.Rows[93][0].ToString();
        HI_TAB2_1.NavigateUrl = dt.Rows[94][1].ToString();
        HI_TAB2_1.ImageUrl = "image/lelecoco/" + dt.Rows[94][2].ToString();
        HI_TAB2_2.NavigateUrl = dt.Rows[95][1].ToString();
        HI_TAB2_2.ImageUrl = "image/lelecoco/" + dt.Rows[95][2].ToString();
        HI_TAB2_3.NavigateUrl = dt.Rows[96][1].ToString();
        HI_TAB2_3.ImageUrl = "image/lelecoco/" + dt.Rows[96][2].ToString();
        HI_TAB2_4.NavigateUrl = dt.Rows[97][1].ToString();
        HI_TAB2_4.ImageUrl = "image/lelecoco/" + dt.Rows[97][2].ToString();
        HI_TAB2_5.NavigateUrl = dt.Rows[98][1].ToString();
        HI_TAB2_5.ImageUrl = "image/lelecoco/" + dt.Rows[98][2].ToString();

        HI_Tab3IMG.Text = dt.Rows[99][0].ToString();
        HI_TAB3_1.NavigateUrl = dt.Rows[100][1].ToString();
        HI_TAB3_1.ImageUrl = "image/lelecoco/" + dt.Rows[100][2].ToString();
        HI_TAB3_2.NavigateUrl = dt.Rows[101][1].ToString();
        HI_TAB3_2.ImageUrl = "image/lelecoco/" + dt.Rows[101][2].ToString();
        HI_TAB3_3.NavigateUrl = dt.Rows[102][1].ToString();
        HI_TAB3_3.ImageUrl = "image/lelecoco/" + dt.Rows[102][2].ToString();
        HI_TAB3_4.NavigateUrl = dt.Rows[103][1].ToString();
        HI_TAB3_4.ImageUrl = "image/lelecoco/" + dt.Rows[103][2].ToString();
        HI_TAB3_5.NavigateUrl = dt.Rows[104][1].ToString();
        HI_TAB3_5.ImageUrl = "image/lelecoco/" + dt.Rows[104][2].ToString();

        HI_Tab4IMG.Text = dt.Rows[105][0].ToString();
        HI_TAB4_1.NavigateUrl = dt.Rows[106][1].ToString();
        HI_TAB4_1.ImageUrl = "image/lelecoco/" + dt.Rows[106][2].ToString();
        HI_TAB4_2.NavigateUrl = dt.Rows[107][1].ToString();
        HI_TAB4_2.ImageUrl = "image/lelecoco/" + dt.Rows[107][2].ToString();
        HI_TAB4_3.NavigateUrl = dt.Rows[108][1].ToString();
        HI_TAB4_3.ImageUrl = "image/lelecoco/" + dt.Rows[108][2].ToString();
        HI_TAB4_4.NavigateUrl = dt.Rows[109][1].ToString();
        HI_TAB4_4.ImageUrl = "image/lelecoco/" + dt.Rows[109][2].ToString();
        HI_TAB4_5.NavigateUrl = dt.Rows[110][1].ToString();
        HI_TAB4_5.ImageUrl = "image/lelecoco/" + dt.Rows[110][2].ToString();

        HI_Tab5IMG.Text = dt.Rows[111][0].ToString();
        HI_TAB5_1.NavigateUrl = dt.Rows[112][1].ToString();
        HI_TAB5_1.ImageUrl = "image/lelecoco/" + dt.Rows[112][2].ToString();
        HI_TAB5_2.NavigateUrl = dt.Rows[113][1].ToString();
        HI_TAB5_2.ImageUrl = "image/lelecoco/" + dt.Rows[113][2].ToString();
        HI_TAB5_3.NavigateUrl = dt.Rows[114][1].ToString();
        HI_TAB5_3.ImageUrl = "image/lelecoco/" + dt.Rows[114][2].ToString();
        HI_TAB5_4.NavigateUrl = dt.Rows[115][1].ToString();
        HI_TAB5_4.ImageUrl = "image/lelecoco/" + dt.Rows[115][2].ToString();
        HI_TAB5_5.NavigateUrl = dt.Rows[116][1].ToString();
        HI_TAB5_5.ImageUrl = "image/lelecoco/" + dt.Rows[116][2].ToString();

        VIP_main_m1_L1H.Text = dt.Rows[117][0].ToString();
        VIP_main_m1_L1C.NavigateUrl = dt.Rows[117][1].ToString();
        VIP_main_m1_L1C.ImageUrl = "image/lelecoco/" + dt.Rows[117][2].ToString();
        VIP_main_m1_L1C1.NavigateUrl = dt.Rows[118][1].ToString();
        VIP_main_m1_L1C1.ImageUrl = "image/lelecoco/" + dt.Rows[118][2].ToString();
        VIP_main_m1_L1C2.NavigateUrl = dt.Rows[119][1].ToString();
        VIP_main_m1_L1C2.ImageUrl = "image/lelecoco/" + dt.Rows[119][2].ToString();
        VIP_main_m1_L2H.Text = dt.Rows[120][0].ToString();
        VIP_main_m1_L2C.NavigateUrl = dt.Rows[120][1].ToString();
        VIP_main_m1_L2C.ImageUrl = "image/lelecoco/" + dt.Rows[120][2].ToString();
        VIP_main_m1_L2C1.NavigateUrl = dt.Rows[121][1].ToString();
        VIP_main_m1_L2C1.ImageUrl = "image/lelecoco/" + dt.Rows[121][2].ToString();
        VIP_main_m1_L2C2.NavigateUrl = dt.Rows[122][1].ToString();
        VIP_main_m1_L2C2.ImageUrl = "image/lelecoco/" + dt.Rows[122][2].ToString();
        VIP_main_m1_L3H.Text = dt.Rows[123][0].ToString();
        VIP_main_m1_L3C.NavigateUrl = dt.Rows[123][1].ToString();
        VIP_main_m1_L3C.ImageUrl = "image/lelecoco/" + dt.Rows[123][2].ToString();
        VIP_main_m1_L3C1.NavigateUrl = dt.Rows[124][1].ToString();
        VIP_main_m1_L3C1.ImageUrl = "image/lelecoco/" + dt.Rows[124][2].ToString();
        VIP_main_m1_L3C2.NavigateUrl = dt.Rows[125][1].ToString();
        VIP_main_m1_L3C2.ImageUrl = "image/lelecoco/" + dt.Rows[125][2].ToString();
        VIP_main_m1_L4H.Text = dt.Rows[126][0].ToString();
        VIP_main_m1_L4C.NavigateUrl = dt.Rows[126][1].ToString();
        VIP_main_m1_L4C.ImageUrl = "image/lelecoco/" + dt.Rows[126][2].ToString();
        VIP_main_m1_L4C1.NavigateUrl = dt.Rows[127][1].ToString();
        VIP_main_m1_L4C1.ImageUrl = "image/lelecoco/" + dt.Rows[127][2].ToString();
        VIP_main_m1_L4C2.NavigateUrl = dt.Rows[128][1].ToString();
        VIP_main_m1_L4C2.ImageUrl = "image/lelecoco/" + dt.Rows[128][2].ToString();

        VIP_main_m1_L5H.Text = dt.Rows[129][0].ToString();
        VIP_main_m1_L5C.NavigateUrl = dt.Rows[129][1].ToString();
        VIP_main_m1_L5C.ImageUrl = "image/lelecoco/" + dt.Rows[129][2].ToString();
        VIP_main_m1_L5C1.NavigateUrl = dt.Rows[130][1].ToString();
        VIP_main_m1_L5C1.ImageUrl = "image/lelecoco/" + dt.Rows[130][2].ToString();
        VIP_main_m1_L5C2.NavigateUrl = dt.Rows[131][1].ToString();
        VIP_main_m1_L5C2.ImageUrl = "image/lelecoco/" + dt.Rows[131][2].ToString();
        VIP_main_m1_L6H.Text = dt.Rows[132][0].ToString();
        VIP_main_m1_L6C.NavigateUrl = dt.Rows[132][1].ToString();
        VIP_main_m1_L6C.ImageUrl = "image/lelecoco/" + dt.Rows[132][2].ToString();
        VIP_main_m1_L6C1.NavigateUrl = dt.Rows[133][1].ToString();
        VIP_main_m1_L6C1.ImageUrl = "image/lelecoco/" + dt.Rows[133][2].ToString();
        VIP_main_m1_L6C2.NavigateUrl = dt.Rows[134][1].ToString();
        VIP_main_m1_L6C2.ImageUrl = "image/lelecoco/" + dt.Rows[134][2].ToString();
        VIP_main_m1_L7H.Text = dt.Rows[135][0].ToString();
        VIP_main_m1_L7C.NavigateUrl = dt.Rows[135][1].ToString();
        VIP_main_m1_L7C.ImageUrl = "image/lelecoco/" + dt.Rows[135][2].ToString();
        VIP_main_m1_L7C1.NavigateUrl = dt.Rows[136][1].ToString();
        VIP_main_m1_L7C1.ImageUrl = "image/lelecoco/" + dt.Rows[136][2].ToString();
        VIP_main_m1_L7C2.NavigateUrl = dt.Rows[137][1].ToString();
        VIP_main_m1_L7C2.ImageUrl = "image/lelecoco/" + dt.Rows[137][2].ToString();
        VIP_main_m1_L8H.Text = dt.Rows[138][0].ToString();
        VIP_main_m1_L8C.NavigateUrl = dt.Rows[138][1].ToString();
        VIP_main_m1_L8C.ImageUrl = "image/lelecoco/" + dt.Rows[138][2].ToString();
        VIP_main_m1_L8C1.NavigateUrl = dt.Rows[139][1].ToString();
        VIP_main_m1_L8C1.ImageUrl = "image/lelecoco/" + dt.Rows[139][2].ToString();
        VIP_main_m1_L8C2.NavigateUrl = dt.Rows[140][1].ToString();
        VIP_main_m1_L8C2.ImageUrl = "image/lelecoco/" + dt.Rows[140][2].ToString();

        VIP_main_m1_L9H.Text = dt.Rows[141][0].ToString();
        VIP_main_m1_L9C.NavigateUrl = dt.Rows[141][1].ToString();
        VIP_main_m1_L9C.ImageUrl = "image/lelecoco/" + dt.Rows[141][2].ToString();
        VIP_main_m1_L9C1.NavigateUrl = dt.Rows[142][1].ToString();
        VIP_main_m1_L9C1.ImageUrl = "image/lelecoco/" + dt.Rows[142][2].ToString();
        VIP_main_m1_L9C2.NavigateUrl = dt.Rows[143][1].ToString();
        VIP_main_m1_L9C2.ImageUrl = "image/lelecoco/" + dt.Rows[143][2].ToString();
        VIP_main_m1_L10H.Text = dt.Rows[144][0].ToString();
        VIP_main_m1_L10C.NavigateUrl = dt.Rows[144][1].ToString();
        VIP_main_m1_L10C.ImageUrl = "image/lelecoco/" + dt.Rows[144][2].ToString();
        VIP_main_m1_L10C1.NavigateUrl = dt.Rows[145][1].ToString();
        VIP_main_m1_L10C1.ImageUrl = "image/lelecoco/" + dt.Rows[145][2].ToString();
        VIP_main_m1_L10C2.NavigateUrl = dt.Rows[146][1].ToString();
        VIP_main_m1_L10C2.ImageUrl = "image/lelecoco/" + dt.Rows[146][2].ToString();
        VIP_main_m1_L11H.Text = dt.Rows[147][0].ToString();
        VIP_main_m1_L11C.NavigateUrl = dt.Rows[147][1].ToString();
        VIP_main_m1_L11C.ImageUrl = "image/lelecoco/" + dt.Rows[147][2].ToString();
        VIP_main_m1_L11C1.NavigateUrl = dt.Rows[148][1].ToString();
        VIP_main_m1_L11C1.ImageUrl = "image/lelecoco/" + dt.Rows[148][2].ToString();
        VIP_main_m1_L11C2.NavigateUrl = dt.Rows[149][1].ToString();
        VIP_main_m1_L11C2.ImageUrl = "image/lelecoco/" + dt.Rows[149][2].ToString();
        VIP_main_m1_L12H.Text = dt.Rows[150][0].ToString();
        VIP_main_m1_L12C.NavigateUrl = dt.Rows[150][1].ToString();
        VIP_main_m1_L12C.ImageUrl = "image/lelecoco/" + dt.Rows[150][2].ToString();
        VIP_main_m1_L12C1.NavigateUrl = dt.Rows[151][1].ToString();
        VIP_main_m1_L12C1.ImageUrl = "image/lelecoco/" + dt.Rows[151][2].ToString();
        VIP_main_m1_L12C2.NavigateUrl = dt.Rows[152][1].ToString();
        VIP_main_m1_L12C2.ImageUrl = "image/lelecoco/" + dt.Rows[152][2].ToString();

        VIP_main_m1_L13H.Text = dt.Rows[153][0].ToString();
        VIP_main_m1_L13C.NavigateUrl = dt.Rows[153][1].ToString();
        VIP_main_m1_L13C.ImageUrl = "image/lelecoco/" + dt.Rows[153][2].ToString();
        VIP_main_m1_L13C1.NavigateUrl = dt.Rows[154][1].ToString();
        VIP_main_m1_L13C1.ImageUrl = "image/lelecoco/" + dt.Rows[154][2].ToString();
        VIP_main_m1_L13C2.NavigateUrl = dt.Rows[155][1].ToString();
        VIP_main_m1_L13C2.ImageUrl = "image/lelecoco/" + dt.Rows[155][2].ToString();
        VIP_main_m1_L14H.Text = dt.Rows[156][0].ToString();
        VIP_main_m1_L14C.NavigateUrl = dt.Rows[156][1].ToString();
        VIP_main_m1_L14C.ImageUrl = "image/lelecoco/" + dt.Rows[156][2].ToString();
        VIP_main_m1_L14C1.NavigateUrl = dt.Rows[157][1].ToString();
        VIP_main_m1_L14C1.ImageUrl = "image/lelecoco/" + dt.Rows[157][2].ToString();
        VIP_main_m1_L14C2.NavigateUrl = dt.Rows[158][1].ToString();
        VIP_main_m1_L14C2.ImageUrl = "image/lelecoco/" + dt.Rows[158][2].ToString();
        VIP_main_m1_L15H.Text = dt.Rows[159][0].ToString();
        VIP_main_m1_L15C.NavigateUrl = dt.Rows[159][1].ToString();
        VIP_main_m1_L15C.ImageUrl = "image/lelecoco/" + dt.Rows[159][2].ToString();
        VIP_main_m1_L15C1.NavigateUrl = dt.Rows[160][1].ToString();
        VIP_main_m1_L15C1.ImageUrl = "image/lelecoco/" + dt.Rows[160][2].ToString();
        VIP_main_m1_L15C2.NavigateUrl = dt.Rows[161][1].ToString();
        VIP_main_m1_L15C2.ImageUrl = "image/lelecoco/" + dt.Rows[161][2].ToString();
        VIP_main_m1_L16H.Text = dt.Rows[162][0].ToString();
        VIP_main_m1_L16C.NavigateUrl = dt.Rows[162][1].ToString();
        VIP_main_m1_L16C.ImageUrl = "image/lelecoco/" + dt.Rows[162][2].ToString();
        VIP_main_m1_L16C1.NavigateUrl = dt.Rows[163][1].ToString();
        VIP_main_m1_L16C1.ImageUrl = "image/lelecoco/" + dt.Rows[163][2].ToString();
        VIP_main_m1_L16C2.NavigateUrl = dt.Rows[164][1].ToString();
        VIP_main_m1_L16C2.ImageUrl = "image/lelecoco/" + dt.Rows[164][2].ToString();

        VIP_main_m1_L17H.Text = dt.Rows[221][0].ToString();
        VIP_main_m1_L17C.NavigateUrl = dt.Rows[221][1].ToString();
        VIP_main_m1_L17C.ImageUrl = "image/lelecoco/" + dt.Rows[221][2].ToString();
        VIP_main_m1_L17C1.NavigateUrl = dt.Rows[222][1].ToString();
        VIP_main_m1_L17C1.ImageUrl = "image/lelecoco/" + dt.Rows[222][2].ToString();
        VIP_main_m1_L17C2.NavigateUrl = dt.Rows[223][1].ToString();
        VIP_main_m1_L17C2.ImageUrl = "image/lelecoco/" + dt.Rows[223][2].ToString();
        VIP_main_m1_L18H.Text = dt.Rows[224][0].ToString();
        VIP_main_m1_L18C.NavigateUrl = dt.Rows[224][1].ToString();
        VIP_main_m1_L18C.ImageUrl = "image/lelecoco/" + dt.Rows[224][2].ToString();
        VIP_main_m1_L18C1.NavigateUrl = dt.Rows[225][1].ToString();
        VIP_main_m1_L18C1.ImageUrl = "image/lelecoco/" + dt.Rows[225][2].ToString();
        VIP_main_m1_L18C2.NavigateUrl = dt.Rows[226][1].ToString();
        VIP_main_m1_L18C2.ImageUrl = "image/lelecoco/" + dt.Rows[226][2].ToString();
        VIP_main_m1_L19H.Text = dt.Rows[227][0].ToString();
        VIP_main_m1_L19C.NavigateUrl = dt.Rows[227][1].ToString();
        VIP_main_m1_L19C.ImageUrl = "image/lelecoco/" + dt.Rows[227][2].ToString();
        VIP_main_m1_L19C1.NavigateUrl = dt.Rows[228][1].ToString();
        VIP_main_m1_L19C1.ImageUrl = "image/lelecoco/" + dt.Rows[228][2].ToString();
        VIP_main_m1_L19C2.NavigateUrl = dt.Rows[229][1].ToString();
        VIP_main_m1_L19C2.ImageUrl = "image/lelecoco/" + dt.Rows[229][2].ToString();
        VIP_main_m1_L20H.Text = dt.Rows[230][0].ToString();
        VIP_main_m1_L20C.NavigateUrl = dt.Rows[230][1].ToString();
        VIP_main_m1_L20C.ImageUrl = "image/lelecoco/" + dt.Rows[230][2].ToString();
        VIP_main_m1_L20C1.NavigateUrl = dt.Rows[231][1].ToString();
        VIP_main_m1_L20C1.ImageUrl = "image/lelecoco/" + dt.Rows[231][2].ToString();
        VIP_main_m1_L20C2.NavigateUrl = dt.Rows[232][1].ToString();
        VIP_main_m1_L20C2.ImageUrl = "image/lelecoco/" + dt.Rows[232][2].ToString();

        VIP_main_m1_L21H.Text = dt.Rows[233][0].ToString();
        VIP_main_m1_L21C.NavigateUrl = dt.Rows[233][1].ToString();
        VIP_main_m1_L21C.ImageUrl = "image/lelecoco/" + dt.Rows[233][2].ToString();
        VIP_main_m1_L21C1.NavigateUrl = dt.Rows[234][1].ToString();
        VIP_main_m1_L21C1.ImageUrl = "image/lelecoco/" + dt.Rows[234][2].ToString();
        VIP_main_m1_L21C2.NavigateUrl = dt.Rows[235][1].ToString();
        VIP_main_m1_L21C2.ImageUrl = "image/lelecoco/" + dt.Rows[235][2].ToString();
        VIP_main_m1_L22H.Text = dt.Rows[236][0].ToString();
        VIP_main_m1_L22C.NavigateUrl = dt.Rows[236][1].ToString();
        VIP_main_m1_L22C.ImageUrl = "image/lelecoco/" + dt.Rows[236][2].ToString();
        VIP_main_m1_L22C1.NavigateUrl = dt.Rows[237][1].ToString();
        VIP_main_m1_L22C1.ImageUrl = "image/lelecoco/" + dt.Rows[237][2].ToString();
        VIP_main_m1_L22C2.NavigateUrl = dt.Rows[238][1].ToString();
        VIP_main_m1_L22C2.ImageUrl = "image/lelecoco/" + dt.Rows[238][2].ToString();
        VIP_main_m1_L23H.Text = dt.Rows[239][0].ToString();
        VIP_main_m1_L23C.NavigateUrl = dt.Rows[239][1].ToString();
        VIP_main_m1_L23C.ImageUrl = "image/lelecoco/" + dt.Rows[239][2].ToString();
        VIP_main_m1_L23C1.NavigateUrl = dt.Rows[240][1].ToString();
        VIP_main_m1_L23C1.ImageUrl = "image/lelecoco/" + dt.Rows[240][2].ToString();
        VIP_main_m1_L23C2.NavigateUrl = dt.Rows[241][1].ToString();
        VIP_main_m1_L23C2.ImageUrl = "image/lelecoco/" + dt.Rows[241][2].ToString();
        VIP_main_m1_L24H.Text = dt.Rows[242][0].ToString();
        VIP_main_m1_L24C.NavigateUrl = dt.Rows[242][1].ToString();
        VIP_main_m1_L24C.ImageUrl = "image/lelecoco/" + dt.Rows[242][2].ToString();
        VIP_main_m1_L24C1.NavigateUrl = dt.Rows[243][1].ToString();
        VIP_main_m1_L24C1.ImageUrl = "image/lelecoco/" + dt.Rows[243][2].ToString();
        VIP_main_m1_L24C2.NavigateUrl = dt.Rows[244][1].ToString();
        VIP_main_m1_L24C2.ImageUrl = "image/lelecoco/" + dt.Rows[244][2].ToString();

        VIP_main_m1_L25H.Text = dt.Rows[245][0].ToString();
        VIP_main_m1_L25C.NavigateUrl = dt.Rows[245][1].ToString();
        VIP_main_m1_L25C.ImageUrl = "image/lelecoco/" + dt.Rows[245][2].ToString();
        VIP_main_m1_L25C1.NavigateUrl = dt.Rows[246][1].ToString();
        VIP_main_m1_L25C1.ImageUrl = "image/lelecoco/" + dt.Rows[246][2].ToString();
        VIP_main_m1_L25C2.NavigateUrl = dt.Rows[247][1].ToString();
        VIP_main_m1_L25C2.ImageUrl = "image/lelecoco/" + dt.Rows[247][2].ToString();
        VIP_main_m1_L26H.Text = dt.Rows[248][0].ToString();
        VIP_main_m1_L26C.NavigateUrl = dt.Rows[248][1].ToString();
        VIP_main_m1_L26C.ImageUrl = "image/lelecoco/" + dt.Rows[248][2].ToString();
        VIP_main_m1_L26C1.NavigateUrl = dt.Rows[249][1].ToString();
        VIP_main_m1_L26C1.ImageUrl = "image/lelecoco/" + dt.Rows[249][2].ToString();
        VIP_main_m1_L26C2.NavigateUrl = dt.Rows[250][1].ToString();
        VIP_main_m1_L26C2.ImageUrl = "image/lelecoco/" + dt.Rows[250][2].ToString();
        VIP_main_m1_L27H.Text = dt.Rows[251][0].ToString();
        VIP_main_m1_L27C.NavigateUrl = dt.Rows[251][1].ToString();
        VIP_main_m1_L27C.ImageUrl = "image/lelecoco/" + dt.Rows[251][2].ToString();
        VIP_main_m1_L27C1.NavigateUrl = dt.Rows[252][1].ToString();
        VIP_main_m1_L27C1.ImageUrl = "image/lelecoco/" + dt.Rows[252][2].ToString();
        VIP_main_m1_L27C2.NavigateUrl = dt.Rows[253][1].ToString();
        VIP_main_m1_L27C2.ImageUrl = "image/lelecoco/" + dt.Rows[253][2].ToString();
        VIP_main_m1_L28H.Text = dt.Rows[254][0].ToString();
        VIP_main_m1_L28C.NavigateUrl = dt.Rows[254][1].ToString();
        VIP_main_m1_L28C.ImageUrl = "image/lelecoco/" + dt.Rows[254][2].ToString();
        VIP_main_m1_L28C1.NavigateUrl = dt.Rows[255][1].ToString();
        VIP_main_m1_L28C1.ImageUrl = "image/lelecoco/" + dt.Rows[255][2].ToString();
        VIP_main_m1_L28C2.NavigateUrl = dt.Rows[256][1].ToString();
        VIP_main_m1_L28C2.ImageUrl = "image/lelecoco/" + dt.Rows[256][2].ToString();

        VIP_main_m1_L29H.Text = dt.Rows[257][0].ToString();
        VIP_main_m1_L29C.NavigateUrl = dt.Rows[257][1].ToString();
        VIP_main_m1_L29C.ImageUrl = "image/lelecoco/" + dt.Rows[257][2].ToString();
        VIP_main_m1_L29C1.NavigateUrl = dt.Rows[258][1].ToString();
        VIP_main_m1_L29C1.ImageUrl = "image/lelecoco/" + dt.Rows[258][2].ToString();
        VIP_main_m1_L29C2.NavigateUrl = dt.Rows[259][1].ToString();
        VIP_main_m1_L29C2.ImageUrl = "image/lelecoco/" + dt.Rows[259][2].ToString();
        VIP_main_m1_L30H.Text = dt.Rows[260][0].ToString();
        VIP_main_m1_L30C.NavigateUrl = dt.Rows[260][1].ToString();
        VIP_main_m1_L30C.ImageUrl = "image/lelecoco/" + dt.Rows[260][2].ToString();
        VIP_main_m1_L30C1.NavigateUrl = dt.Rows[261][1].ToString();
        VIP_main_m1_L30C1.ImageUrl = "image/lelecoco/" + dt.Rows[261][2].ToString();
        VIP_main_m1_L30C2.NavigateUrl = dt.Rows[262][1].ToString();
        VIP_main_m1_L30C2.ImageUrl = "image/lelecoco/" + dt.Rows[262][2].ToString();
        VIP_main_m1_L31H.Text = dt.Rows[263][0].ToString();
        VIP_main_m1_L31C.NavigateUrl = dt.Rows[263][1].ToString();
        VIP_main_m1_L31C.ImageUrl = "image/lelecoco/" + dt.Rows[263][2].ToString();
        VIP_main_m1_L31C1.NavigateUrl = dt.Rows[264][1].ToString();
        VIP_main_m1_L31C1.ImageUrl = "image/lelecoco/" + dt.Rows[264][2].ToString();
        VIP_main_m1_L31C2.NavigateUrl = dt.Rows[265][1].ToString();
        VIP_main_m1_L31C2.ImageUrl = "image/lelecoco/" + dt.Rows[265][2].ToString();
        VIP_main_m1_L32H.Text = dt.Rows[266][0].ToString();
        VIP_main_m1_L32C.NavigateUrl = dt.Rows[266][1].ToString();
        VIP_main_m1_L32C.ImageUrl = "image/lelecoco/" + dt.Rows[266][2].ToString();
        VIP_main_m1_L32C1.NavigateUrl = dt.Rows[267][1].ToString();
        VIP_main_m1_L32C1.ImageUrl = "image/lelecoco/" + dt.Rows[267][2].ToString();
        VIP_main_m1_L32C2.NavigateUrl = dt.Rows[268][1].ToString();
        VIP_main_m1_L32C2.ImageUrl = "image/lelecoco/" + dt.Rows[268][2].ToString();

        VIP_main_m1_L33H.Text = dt.Rows[269][0].ToString();
        VIP_main_m1_L33C.NavigateUrl = dt.Rows[269][1].ToString();
        VIP_main_m1_L33C.ImageUrl = "image/lelecoco/" + dt.Rows[269][2].ToString();
        VIP_main_m1_L33C1.NavigateUrl = dt.Rows[270][1].ToString();
        VIP_main_m1_L33C1.ImageUrl = "image/lelecoco/" + dt.Rows[270][2].ToString();
        VIP_main_m1_L33C2.NavigateUrl = dt.Rows[271][1].ToString();
        VIP_main_m1_L33C2.ImageUrl = "image/lelecoco/" + dt.Rows[271][2].ToString();
        VIP_main_m1_L34H.Text = dt.Rows[272][0].ToString();
        VIP_main_m1_L34C.NavigateUrl = dt.Rows[272][1].ToString();
        VIP_main_m1_L34C.ImageUrl = "image/lelecoco/" + dt.Rows[272][2].ToString();
        VIP_main_m1_L34C1.NavigateUrl = dt.Rows[273][1].ToString();
        VIP_main_m1_L34C1.ImageUrl = "image/lelecoco/" + dt.Rows[273][2].ToString();
        VIP_main_m1_L34C2.NavigateUrl = dt.Rows[274][1].ToString();
        VIP_main_m1_L34C2.ImageUrl = "image/lelecoco/" + dt.Rows[274][2].ToString();
        VIP_main_m1_L35H.Text = dt.Rows[275][0].ToString();
        VIP_main_m1_L35C.NavigateUrl = dt.Rows[275][1].ToString();
        VIP_main_m1_L35C.ImageUrl = "image/lelecoco/" + dt.Rows[275][2].ToString();
        VIP_main_m1_L35C1.NavigateUrl = dt.Rows[276][1].ToString();
        VIP_main_m1_L35C1.ImageUrl = "image/lelecoco/" + dt.Rows[276][2].ToString();
        VIP_main_m1_L35C2.NavigateUrl = dt.Rows[277][1].ToString();
        VIP_main_m1_L35C2.ImageUrl = "image/lelecoco/" + dt.Rows[277][2].ToString();
        VIP_main_m1_L36H.Text = dt.Rows[278][0].ToString();
        VIP_main_m1_L36C.NavigateUrl = dt.Rows[278][1].ToString();
        VIP_main_m1_L36C.ImageUrl = "image/lelecoco/" + dt.Rows[278][2].ToString();
        VIP_main_m1_L36C1.NavigateUrl = dt.Rows[279][1].ToString();
        VIP_main_m1_L36C1.ImageUrl = "image/lelecoco/" + dt.Rows[279][2].ToString();
        VIP_main_m1_L36C2.NavigateUrl = dt.Rows[280][1].ToString();
        VIP_main_m1_L36C2.ImageUrl = "image/lelecoco/" + dt.Rows[280][2].ToString();

        VIP_main_m1_L37H.Text = dt.Rows[281][0].ToString();
        VIP_main_m1_L37C.NavigateUrl = dt.Rows[281][1].ToString();
        VIP_main_m1_L37C.ImageUrl = "image/lelecoco/" + dt.Rows[281][2].ToString();
        VIP_main_m1_L37C1.NavigateUrl = dt.Rows[282][1].ToString();
        VIP_main_m1_L37C1.ImageUrl = "image/lelecoco/" + dt.Rows[282][2].ToString();
        VIP_main_m1_L37C2.NavigateUrl = dt.Rows[283][1].ToString();
        VIP_main_m1_L37C2.ImageUrl = "image/lelecoco/" + dt.Rows[283][2].ToString();
        VIP_main_m1_L38H.Text = dt.Rows[284][0].ToString();
        VIP_main_m1_L38C.NavigateUrl = dt.Rows[284][1].ToString();
        VIP_main_m1_L38C.ImageUrl = "image/lelecoco/" + dt.Rows[284][2].ToString();
        VIP_main_m1_L38C1.NavigateUrl = dt.Rows[285][1].ToString();
        VIP_main_m1_L38C1.ImageUrl = "image/lelecoco/" + dt.Rows[285][2].ToString();
        VIP_main_m1_L38C2.NavigateUrl = dt.Rows[286][1].ToString();
        VIP_main_m1_L38C2.ImageUrl = "image/lelecoco/" + dt.Rows[286][2].ToString();
        VIP_main_m1_L39H.Text = dt.Rows[287][0].ToString();
        VIP_main_m1_L39C.NavigateUrl = dt.Rows[287][1].ToString();
        VIP_main_m1_L39C.ImageUrl = "image/lelecoco/" + dt.Rows[287][2].ToString();
        VIP_main_m1_L39C1.NavigateUrl = dt.Rows[288][1].ToString();
        VIP_main_m1_L39C1.ImageUrl = "image/lelecoco/" + dt.Rows[288][2].ToString();
        VIP_main_m1_L39C2.NavigateUrl = dt.Rows[289][1].ToString();
        VIP_main_m1_L39C2.ImageUrl = "image/lelecoco/" + dt.Rows[289][2].ToString();
        VIP_main_m1_L40H.Text = dt.Rows[290][0].ToString();
        VIP_main_m1_L40C.NavigateUrl = dt.Rows[290][1].ToString();
        VIP_main_m1_L40C.ImageUrl = "image/lelecoco/" + dt.Rows[290][2].ToString();
        VIP_main_m1_L40C1.NavigateUrl = dt.Rows[291][1].ToString();
        VIP_main_m1_L40C1.ImageUrl = "image/lelecoco/" + dt.Rows[291][2].ToString();
        VIP_main_m1_L40C2.NavigateUrl = dt.Rows[292][1].ToString();
        VIP_main_m1_L40C2.ImageUrl = "image/lelecoco/" + dt.Rows[292][2].ToString();

        VIP_main_m1_L41H.Text = dt.Rows[293][0].ToString();
        VIP_main_m1_L41C.NavigateUrl = dt.Rows[293][1].ToString();
        VIP_main_m1_L41C.ImageUrl = "image/lelecoco/" + dt.Rows[293][2].ToString();
        VIP_main_m1_L41C1.NavigateUrl = dt.Rows[294][1].ToString();
        VIP_main_m1_L41C1.ImageUrl = "image/lelecoco/" + dt.Rows[294][2].ToString();
        VIP_main_m1_L41C2.NavigateUrl = dt.Rows[295][1].ToString();
        VIP_main_m1_L41C2.ImageUrl = "image/lelecoco/" + dt.Rows[295][2].ToString();
        VIP_main_m1_L42H.Text = dt.Rows[296][0].ToString();
        VIP_main_m1_L42C.NavigateUrl = dt.Rows[296][1].ToString();
        VIP_main_m1_L42C.ImageUrl = "image/lelecoco/" + dt.Rows[296][2].ToString();
        VIP_main_m1_L42C1.NavigateUrl = dt.Rows[297][1].ToString();
        VIP_main_m1_L42C1.ImageUrl = "image/lelecoco/" + dt.Rows[297][2].ToString();
        VIP_main_m1_L42C2.NavigateUrl = dt.Rows[298][1].ToString();
        VIP_main_m1_L42C2.ImageUrl = "image/lelecoco/" + dt.Rows[298][2].ToString();
        VIP_main_m1_L43H.Text = dt.Rows[299][0].ToString();
        VIP_main_m1_L43C.NavigateUrl = dt.Rows[299][1].ToString();
        VIP_main_m1_L43C.ImageUrl = "image/lelecoco/" + dt.Rows[299][2].ToString();
        VIP_main_m1_L43C1.NavigateUrl = dt.Rows[300][1].ToString();
        VIP_main_m1_L43C1.ImageUrl = "image/lelecoco/" + dt.Rows[300][2].ToString();
        VIP_main_m1_L43C2.NavigateUrl = dt.Rows[301][1].ToString();
        VIP_main_m1_L43C2.ImageUrl = "image/lelecoco/" + dt.Rows[301][2].ToString();
        VIP_main_m1_L44H.Text = dt.Rows[302][0].ToString();
        VIP_main_m1_L44C.NavigateUrl = dt.Rows[302][1].ToString();
        VIP_main_m1_L44C.ImageUrl = "image/lelecoco/" + dt.Rows[302][2].ToString();
        VIP_main_m1_L44C1.NavigateUrl = dt.Rows[303][1].ToString();
        VIP_main_m1_L44C1.ImageUrl = "image/lelecoco/" + dt.Rows[303][2].ToString();
        VIP_main_m1_L44C2.NavigateUrl = dt.Rows[304][1].ToString();
        VIP_main_m1_L44C2.ImageUrl = "image/lelecoco/" + dt.Rows[304][2].ToString();

        VIP_main_m1_L45H.Text = dt.Rows[305][0].ToString();
        VIP_main_m1_L45C.NavigateUrl = dt.Rows[305][1].ToString();
        VIP_main_m1_L45C.ImageUrl = "image/lelecoco/" + dt.Rows[305][2].ToString();
        VIP_main_m1_L45C1.NavigateUrl = dt.Rows[306][1].ToString();
        VIP_main_m1_L45C1.ImageUrl = "image/lelecoco/" + dt.Rows[306][2].ToString();
        VIP_main_m1_L45C2.NavigateUrl = dt.Rows[307][1].ToString();
        VIP_main_m1_L45C2.ImageUrl = "image/lelecoco/" + dt.Rows[307][2].ToString();
        VIP_main_m1_L46H.Text = dt.Rows[308][0].ToString();
        VIP_main_m1_L46C.NavigateUrl = dt.Rows[308][1].ToString();
        VIP_main_m1_L46C.ImageUrl = "image/lelecoco/" + dt.Rows[308][2].ToString();
        VIP_main_m1_L46C1.NavigateUrl = dt.Rows[309][1].ToString();
        VIP_main_m1_L46C1.ImageUrl = "image/lelecoco/" + dt.Rows[309][2].ToString();
        VIP_main_m1_L46C2.NavigateUrl = dt.Rows[310][1].ToString();
        VIP_main_m1_L46C2.ImageUrl = "image/lelecoco/" + dt.Rows[310][2].ToString();
        VIP_main_m1_L47H.Text = dt.Rows[311][0].ToString();
        VIP_main_m1_L47C.NavigateUrl = dt.Rows[311][1].ToString();
        VIP_main_m1_L47C.ImageUrl = "image/lelecoco/" + dt.Rows[311][2].ToString();
        VIP_main_m1_L47C1.NavigateUrl = dt.Rows[312][1].ToString();
        VIP_main_m1_L47C1.ImageUrl = "image/lelecoco/" + dt.Rows[312][2].ToString();
        VIP_main_m1_L47C2.NavigateUrl = dt.Rows[313][1].ToString();
        VIP_main_m1_L47C2.ImageUrl = "image/lelecoco/" + dt.Rows[313][2].ToString();
        VIP_main_m1_L48H.Text = dt.Rows[314][0].ToString();
        VIP_main_m1_L48C.NavigateUrl = dt.Rows[314][1].ToString();
        VIP_main_m1_L48C.ImageUrl = "image/lelecoco/" + dt.Rows[314][2].ToString();
        VIP_main_m1_L48C1.NavigateUrl = dt.Rows[315][1].ToString();
        VIP_main_m1_L48C1.ImageUrl = "image/lelecoco/" + dt.Rows[315][2].ToString();
        VIP_main_m1_L48C2.NavigateUrl = dt.Rows[316][1].ToString();
        VIP_main_m1_L48C2.ImageUrl = "image/lelecoco/" + dt.Rows[316][2].ToString();
        //164 221

        advertising2.NavigateUrl = dt.Rows[165][1].ToString();
        advertising2.ImageUrl = "image/lelecoco/" + dt.Rows[165][2].ToString();

        TB1.NavigateUrl = dt.Rows[166][1].ToString();
        TB1.ImageUrl = "image/lelecoco/" + dt.Rows[166][2].ToString();
        TBT1.Text = dt.Rows[166][0].ToString();
        TBT1.NavigateUrl = dt.Rows[166][1].ToString();

        TB2.NavigateUrl = dt.Rows[167][1].ToString();
        TB2.ImageUrl = "image/lelecoco/" + dt.Rows[167][2].ToString();
        TBT2.Text = dt.Rows[167][0].ToString();
        TBT2.NavigateUrl = dt.Rows[167][1].ToString();

        TB3.NavigateUrl = dt.Rows[168][1].ToString();
        TB3.ImageUrl = "image/lelecoco/" + dt.Rows[168][2].ToString();
        TBT3.Text = dt.Rows[168][0].ToString();
        TBT3.NavigateUrl = dt.Rows[168][1].ToString();

        TB4.NavigateUrl = dt.Rows[169][1].ToString();
        TB4.ImageUrl = "image/lelecoco/" + dt.Rows[169][2].ToString();
        TBT4.Text = dt.Rows[169][0].ToString();
        TBT4.NavigateUrl = dt.Rows[169][1].ToString();

        TB5.NavigateUrl = dt.Rows[170][1].ToString();
        TB5.ImageUrl = "image/lelecoco/" + dt.Rows[170][2].ToString();
        TBT5.Text = dt.Rows[170][0].ToString();
        TBT5.NavigateUrl = dt.Rows[170][1].ToString();

        TB6.NavigateUrl = dt.Rows[171][1].ToString();
        TB6.ImageUrl = "image/lelecoco/" + dt.Rows[171][2].ToString();
        TBT6.Text = dt.Rows[171][0].ToString();
        TBT6.NavigateUrl = dt.Rows[171][1].ToString();

        TB7.NavigateUrl = dt.Rows[172][1].ToString();
        TB7.ImageUrl = "image/lelecoco/" + dt.Rows[172][2].ToString();
        TBT7.Text = dt.Rows[172][0].ToString();
        TBT7.NavigateUrl = dt.Rows[172][1].ToString();

        m3_Popularbrands.Text = dt.Rows[173][0].ToString();
        m3_Popularbrands.NavigateUrl = dt.Rows[173][1].ToString();
        m3_Popularbrands1.Text = "<a href='" + dt.Rows[174][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[174][2].ToString() + "'/></a><a href='" + dt.Rows[175][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[175][2].ToString() + "'/></a><a href='" + dt.Rows[176][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[176][2].ToString() + "'/></a><a href='" + dt.Rows[177][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[177][2].ToString() + "'/></a>";
        m3_Popularbrands2.Text = "<a href='" + dt.Rows[208][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[208][2].ToString() + "'/></a><a href='" + dt.Rows[209][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[209][2].ToString() + "'/></a><a href='" + dt.Rows[210][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[210][2].ToString() + "'/></a><a href='" + dt.Rows[211][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[211][2].ToString() + "'/></a>";
        m3_Popularbrands3.Text = "<a href='" + dt.Rows[212][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[212][2].ToString() + "'/></a><a href='" + dt.Rows[213][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[213][2].ToString() + "'/></a><a href='" + dt.Rows[214][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[214][2].ToString() + "'/></a><a href='" + dt.Rows[215][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[215][2].ToString() + "'/></a>";
        m3_Popularbrands4.Text = "<a href='" + dt.Rows[216][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[216][2].ToString() + "'/></a><a href='" + dt.Rows[217][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[217][2].ToString() + "'/></a><a href='" + dt.Rows[218][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[218][2].ToString() + "'/></a><a href='" + dt.Rows[219][1].ToString() + "'><img src='image/lelecoco/" + dt.Rows[219][2].ToString() + "'/></a>";

        m3_right_L_Webmaster.Text = dt.Rows[178][0].ToString();
        m3_right_L_Webmaster.NavigateUrl = dt.Rows[178][1].ToString();
        m3_right_L_Webmaster1.NavigateUrl = dt.Rows[179][1].ToString();
        m3_right_L_Webmaster1.ImageUrl = "image/lelecoco/" + dt.Rows[179][2].ToString();
        m3_right_L_Webmaster2.NavigateUrl = dt.Rows[180][1].ToString();
        m3_right_L_Webmaster2.ImageUrl = "image/lelecoco/" + dt.Rows[180][2].ToString();
        m3_right_L_Webmaster3.NavigateUrl = dt.Rows[181][1].ToString();
        m3_right_L_Webmaster3.ImageUrl = "image/lelecoco/" + dt.Rows[181][2].ToString();

        m3_right_R_Exclusive.Text = dt.Rows[182][0].ToString();
        m3_right_R_Exclusive.NavigateUrl = dt.Rows[182][1].ToString();
        m3_right_R_Exclusive1.NavigateUrl = dt.Rows[183][1].ToString();
        m3_right_R_Exclusive1.ImageUrl = "image/lelecoco/" + dt.Rows[183][2].ToString();
        m3_right_R_Exclusive2.NavigateUrl = dt.Rows[184][1].ToString();
        m3_right_R_Exclusive2.ImageUrl = "image/lelecoco/" + dt.Rows[184][2].ToString();

        m3_right_L_New.Text = dt.Rows[185][0].ToString();
        m3_right_L_New.NavigateUrl = dt.Rows[185][1].ToString();
        m3_right_L_New1.NavigateUrl = dt.Rows[186][1].ToString();
        m3_right_L_New1.ImageUrl = "image/lelecoco/" + dt.Rows[186][2].ToString();
        m3_right_L_New2.NavigateUrl = dt.Rows[187][1].ToString();
        m3_right_L_New2.ImageUrl = "image/lelecoco/" + dt.Rows[187][2].ToString();
        m3_right_L_New3.NavigateUrl = dt.Rows[188][1].ToString();
        m3_right_L_New3.ImageUrl = "image/lelecoco/" + dt.Rows[188][2].ToString();

        m3_right_L_Member.Text = dt.Rows[189][0].ToString();
        m3_right_L_Member.NavigateUrl = dt.Rows[189][1].ToString();
        m3_right_L_Member1.NavigateUrl = dt.Rows[190][1].ToString();
        m3_right_L_Member1.ImageUrl = "image/lelecoco/" + dt.Rows[190][2].ToString();
        m3_right_L_Member2.NavigateUrl = dt.Rows[191][1].ToString();
        m3_right_L_Member2.ImageUrl = "image/lelecoco/" + dt.Rows[191][2].ToString();

        m3_right_R_Bank.Text = dt.Rows[192][0].ToString();
        m3_right_R_Bank.NavigateUrl = dt.Rows[192][1].ToString();
        m3_right_R_Bank1.NavigateUrl = dt.Rows[193][1].ToString();
        m3_right_R_Bank1.ImageUrl = "image/lelecoco/" + dt.Rows[193][2].ToString();

        advertising3.NavigateUrl = dt.Rows[194][1].ToString();
        advertising3.ImageUrl = "image/lelecoco/" + dt.Rows[194][2].ToString();

        advertising5.NavigateUrl = dt.Rows[195][1].ToString();
        advertising5.ImageUrl = "image/lelecoco/" + dt.Rows[195][2].ToString();

        m4_1T.Text = dt.Rows[196][0].ToString();
        m4_1.NavigateUrl = dt.Rows[196][1].ToString();
        m4_1.ImageUrl = "image/lelecoco/" + dt.Rows[196][2].ToString();
        m4_2T.Text = dt.Rows[197][0].ToString();
        m4_2.NavigateUrl = dt.Rows[197][1].ToString();
        m4_2.ImageUrl = "image/lelecoco/" + dt.Rows[197][2].ToString();
        m4_3T.Text = dt.Rows[198][0].ToString();
        m4_3.NavigateUrl = dt.Rows[198][1].ToString();
        m4_3.ImageUrl = "image/lelecoco/" + dt.Rows[198][2].ToString();
        m4_4T.Text = dt.Rows[199][0].ToString();
        m4_4.NavigateUrl = dt.Rows[199][1].ToString();
        m4_4.ImageUrl = "image/lelecoco/" + dt.Rows[199][2].ToString();
        m4_5T.Text = dt.Rows[200][0].ToString();
        m4_5.NavigateUrl = dt.Rows[200][1].ToString();
        m4_5.ImageUrl = "image/lelecoco/" + dt.Rows[200][2].ToString();
        m4_6T.Text = dt.Rows[201][0].ToString();
        m4_6.NavigateUrl = dt.Rows[201][1].ToString();
        m4_6.ImageUrl = "image/lelecoco/" + dt.Rows[201][2].ToString();
        m4_7T.Text = dt.Rows[202][0].ToString();
        m4_7.NavigateUrl = dt.Rows[202][1].ToString();
        m4_7.ImageUrl = "image/lelecoco/" + dt.Rows[202][2].ToString();
        m4_8T.Text = dt.Rows[203][0].ToString();
        m4_8.NavigateUrl = dt.Rows[203][1].ToString();
        m4_8.ImageUrl = "image/lelecoco/" + dt.Rows[203][2].ToString();
        m4_9T.Text = dt.Rows[204][0].ToString();
        m4_9.NavigateUrl = dt.Rows[204][1].ToString();
        m4_9.ImageUrl = "image/lelecoco/" + dt.Rows[204][2].ToString();
        m4_10T.Text = dt.Rows[205][0].ToString();
        m4_10.NavigateUrl = dt.Rows[205][1].ToString();
        m4_10.ImageUrl = "image/lelecoco/" + dt.Rows[205][2].ToString();
        m4_11T.Text = dt.Rows[206][0].ToString();
        m4_11.NavigateUrl = dt.Rows[206][1].ToString();
        m4_11.ImageUrl = "image/lelecoco/" + dt.Rows[206][2].ToString();
        m4_12T.Text = dt.Rows[207][0].ToString();
        m4_12.NavigateUrl = dt.Rows[207][1].ToString();
        m4_12.ImageUrl = "image/lelecoco/" + dt.Rows[207][2].ToString();
    }
    protected void cal_counter()
    {
        string sql = "select web_counter from web";
        DataTable dt = Mei.GetDataTable(sql);
        int counter;
        if (dt.Rows[0]["web_counter"] == null) { counter = 0; } else { counter = Convert.ToInt32(dt.Rows[0]["web_counter"]); }
        sql = "update web set web_counter = '" + (counter + 1) + "'";
        Mei.connSql(sql);
    }
}